[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "MAS"
version = "0.1.0"

[tool.setuptools.packages.find]
where = ["."]
include = ["virtual_department*"]
