resource_group_name = "mas-dev-rg"
location            = "eastus"
vnet_name           = "mas-dev-vnet"
address_prefix      = "10.0.0.0/16"
subnet_name         = "default"
subnet_prefix       = "10.0.1.0/24"
