name: CI

on:
  push:
    branches: [main, dev, feature/**]
  pull_request:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements-dev.txt') }}
          restore-keys: ${{ runner.os }}-pip-

      - name: Install dev dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: Lint (Ruff + Black + isort)
        run: |
          ruff check .
          black --check .
          isort --check-only .

      - name: Detect secrets
        run: detect-secrets scan --all-files

      - name: Run unit tests with coverage
        env:
          PYTHONPATH: "${{ github.workspace }}"
          # Force coverage data to land in repo root under .coverage
          COVERAGE_FILE: ".coverage"
        run: |
          # Run pytest with coverage
          pytest -q --cov=. --cov-report=xml
          # Merge any parallel coverage data files (safe even if none)
          coverage combine || true
          # Rebuild XML from merged data (idempotent)
          coverage xml -i

      - name: Ensure coverage artifacts exist
        run: |
          echo "Listing repo root after tests:"
          ls -lah .
          if [ ! -f .coverage ]; then
            echo "::error::.coverage not found after pytest/coverage combine!"
            echo "Showing any coverage data fragments:"
            ls -lah .coverage* || true
            exit 1
          fi
          if [ ! -f coverage.xml ]; then
            echo "::error::coverage.xml not found after pytest/coverage xml!"
            exit 1
          fi

      - name: Stage coverage artifacts for upload
        run: |
          mkdir -p coverage-artifacts
          cp .coverage coverage-artifacts/.coverage
          cp coverage.xml coverage-artifacts/coverage.xml
          ls -lah coverage-artifacts

      - uses: actions/upload-artifact@v4
        with:
          name: coverage-xml
          if-no-files-found: error
          path: coverage-artifacts

  infra-plan:
    needs: lint-and-test
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Terraform plan
        run: make infra-plan

      - name: Show plan
        run: terraform -chdir=infrastructure show -no-color plan.out > plan.txt

      - name: Comment plan
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const plan = fs.readFileSync('plan.txt', 'utf8');
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: `## Terraform Plan\n\n\`\`\`\n${plan}\n\`\`\``
            });

  coverage-badge:
    needs: lint-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: coverage-xml
          path: coverage
          merge-multiple: true

      - name: Debug artifact contents
        run: |
          echo "Top level:"
          ls -lah .
          echo "Downloaded coverage artifact contents:"
          ls -lah coverage || true
          echo "coverage-artifacts subdir (if present):"
          ls -lah coverage/coverage-artifacts || true

      - name: Normalize coverage artifact paths
        run: |
          # If upload created a nested coverage-artifacts dir, handle that:
          if [ -d coverage/coverage-artifacts ]; then
            cp coverage/coverage-artifacts/.coverage .coverage
            cp coverage/coverage-artifacts/coverage.xml coverage.xml
          else
            cp coverage/.coverage .coverage
            cp coverage/coverage.xml coverage.xml
          fi
          echo "After copy:"
          ls -lah .
          echo "Showing coverage head:"
          head -20 coverage.xml || true

      - name: Ensure coverage data present
        run: |
          test -f .coverage || (echo ".coverage not found after copy!" && exit 1)
          test -f coverage.xml || (echo "coverage.xml not found after copy!" && exit 1)

      - uses: tj-actions/coverage-badge-py@v2
        with:
          overwrite: true
          # working-directory defaults to "."

      - uses: EndBug/add-and-commit@v9
        with:
          add: "*.svg"
          message: "chore(ci): update coverage badge [skip ci]"

  notify-failure:
    needs: [lint-and-test, coverage-badge]
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - uses: slackapi/slack-github-action@v1
        with:
          payload: |
            {
              "text": "\ud83d\udea8 CI failed on ${{ github.repository }} – <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|details>"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_CI_WEBHOOK }}
