name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
      - name: Run pre-commit
        run: pre-commit run --all-files --show-diff-on-failure

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
          pip install -e .
      - name: Run tests
        run: pytest --cov=virtual_department --cov-report=xml
      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-xml
          path: coverage.xml

  coverage-badge:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install coverage-badge
        run: |
          python -m pip install coverage-badge
      - name: Generate badge
        run: coverage-badge -f -o coverage.svg
      - name: Commit badge
        uses: EndBug/add-and-commit@v9
        with:
          add: 'coverage.svg'
          message: 'Update coverage badge'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
